### ISSUE TITLE
AMD Modules Not Explicitly Defined

### ISSUE THREAD

**Issue by wesley-harding** [strophe/strophejs#109]
The new AMD support is throwing the error below when attempting to use Strophe with AngularJS

    Uncaught Error: See almond README: incorrect module build, no module name

According to the `almond` documentation, this is being caused by modules attempting to anonymously define themselves like this:

    //Example with Base64 module. Issue is with define call
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(function () {
             return factory();
        });
    } else {
        // Browser globals
        root.Base64 = factory();
    }

I suspect this will also cause issues when attempting to use the AMD step in other places since it looks like the pull request for AMD support uses `almond` instead of straight `requirejs`.

To fix the issue, modules need to explicitly provide a name when being defined.  From the Base64 example above, this would be the change.

`define(function()...`  to `define('strophe-base64', function()....`

And likewise for each of the modules currently defined anonymously.

It's late for me today, so I won't have a pull request right now but I'll work on one in the next couple of days. Unless, of course, someone else beats me to it.

**Comment by wesley-harding** [comment]
Pull Request: https://github.com/strophe/strophejs/pull/110

**Comment by jcbrand** [comment]
Thanks @wesley-harding 

AFAIK almond just acts as a stub for require.js when creating a single build from multiple modules/files.
When loading the files individually require.js is still used.

I'm therefore guessing you get this error when trying to make a build, and not when loading the modules individually via require.js, right?

I'm wondering why this issue didn't appear when I was working on this. Perhaps because I set the module names and paths in the Strophe.js build configuration files (main.js which is used by build.js).

I guess you don't use those configuration files, or do you? I'd be curious to know what the differences between the build configurations are.

**Comment by wesley-harding** [comment]
@jcbrand I believe you're correct.  I think the difference for me came in the fact that I'm using Webpack. I didn't dig too far into it, but it looked like the setup I was using (https://github.com/Swiip/generator-gulp-angular) had it setup to use Almond for the packing process.

It also looks like this might have been a recent change to Almond (https://github.com/jrburke/almond#incorrect-module-build-no-module-name) so that could be the contributing factor.

Thanks for the help!
