### ISSUE TITLE
How to hide the password

### ISSUE THREAD

**Issue by pokal4u** [strophe/strophejs#156]
HI,
var username="user1";
var password="userpass";

var connection = new Strophe.Connection(BOSH_SERVICE);
connection.connect(username,password,onConnect);

Above code password was visible for users so How to hide password ?
Because if password opened, users connect directly from rest clients.

How can I restrict this?

Thanks
Pokal

Thanks
Srinivas

**Comment by goors** [comment]
I do not know what framework or programming lang are you using. In order to 'hide' password you have to login on your backend to your xmpp server, make some sort of login listener if you like, an then get rid and sid and login with that.

And this is not issue. Please ask this kind of questions on stackowerflow. There are lot of answers there on this safe login issue.

**Comment by pokal4u** [comment]
HI,
I am using PHP and Strophe.js
I try to login with sid,jid and rid getting error like not-authorised

Thanks
Srinivas

**Comment by jcbrand** [comment]
Use BOSH to create an authenticated XMPP session on the backend of your web application before you serve the page and then pass the RID and SID tokens to your Javascript code.

You then use those tokens to attach to the BOSH session with `connection.attach`.

If you do a search for BOSH and strophe.js you'll find lots of further information.
