### ISSUE TITLE
MUC addHandler for specific room JID

### ISSUE THREAD

**Issue by itay-grudev** [strophe/strophejs#257]
Given the following XMPP stanza:

```xml
<body xmlns='http://jabber.org/protocol/httpbind'>
    <message xml:lang='en' to='3@localhost/BOSH 632224480' from='room-3@conference.example.com/admin@example.com' type='groupchat' id='purple7c785bca' xmlns='jabber:client'>
        <archived by='room-3@conference.example.com' id='1501749888477277' xmlns='urn:xmpp:mam:tmp'/>
        <stanza-id by='room-3@conference.example.com' id='1501749888477277' xmlns='urn:xmpp:sid:0'/>
        <body>Hello World</body>
    </message>
</body>
```

I would expect that the following handler would match the `message` with the `matchBareFromJid` option set to `true`. 

```js
connection.addHandler(
  function( message ) {
      console.log( message.outerHTML )
      return true
    }
  },
  'jabber:client',                 # XML NS
  'message',                       # Name
  'groupchat',                     # Type
  null,                            # ID
  'room-3@conference.example.com', # From
  { 'matchBareFromJid': true }     # Options
)
```

But that's not the case, unless the `from` attribute is `null` and I did expect that _Strophe_ handles the filtering in this case.

**Comment by jcbrand** [comment]
I originally added the `matchBareFromJid` option so that it can be used in converse.js, where it's still being used without problems.

See here:
https://github.com/jcbrand/converse.js/blob/4e491ac5d327eee0013dcf75e323b1a762b87a68/src/converse-muc.js#L1160

I don't set a namespace and I do set the room JID. So perhaps it works if you don't set the NS?
