### ISSUE TITLE
Question: Exporting xhr info with connection status

### ISSUE THREAD

**Issue by damencho** [strophe/strophejs#274]
We are using strophe.js in our project lib-jitsi-meet (used in jitsi-meet https://github.com/jitsi/jitsi-meet).
There are cases in which we need to access the HTTP response headers that are received for the xhr requests.

And also there are some error cases where we need the whole error response text, which I think is not always available, but I'm still testing this cases.

With the changes we are doing we will have access to all the response data.

Just wanted to sync up, is there a better way to do it? And am I in a right direction with my changes? Are you willing to accept such PR?
https://github.com/strophe/strophejs/compare/master...damencho:export-xhr-headers

It is still not finished, no documentation ...

Thanks in advance.

**Comment by jcbrand** [comment]
Strophe.js doesn't just support HTTP/BOSH, but also Websocket connections. By adding `req` to all the methods in `core.js`, you're adding an assumption that BOSH is being used in core code, which is supposed to be transport neutral.

That alone makes this change problematic IMO.

> am I in a right direction with my changes? 

No :)

> is there a better way to do it? 

Looks like you want access to the response in the `this.connect_callback` and that's why you're passing `req` around various methods, so that you can pass it along to `this.connect_callback`.

I think a better way to go about this would be to check whether you don't actually already have the request/response object somewhere on the Strophe.Connection object.

Scanning the code, looks to me like you should be able to access the queue of requests like so:

```
const conn = new Strophe.Connection(url, options);
const requests =  conn._proto._requests;
```

It might be that the relevant request has already been removed from the queue by the time you want to access it. In that case, another viable approach might be to trigger an event at an appropriate time, for example in the `_removeRequest` method in `src/bosh.js`. In your own code you then listen for that event.

**Comment by damencho** [comment]
Here is another proposal: https://github.com/strophe/strophejs/pull/275
If you want I can split the changes into two PRs.

**Comment by jcbrand** [comment]
Looking much better!

I would prefer it if you split the changes into two PRs.

**Comment by damencho** [comment]
Done now there are two separate PRs:
https://github.com/strophe/strophejs/pull/275
https://github.com/strophe/strophejs/pull/276

**Comment by damencho** [comment]
Thanks for merging those! Is there an approximate estimate when there will be a new release?

**Comment by jcbrand** [comment]
Sure thing. We can make a new release in a week or two.

**Comment by damencho** [comment]
Any news on the release?

**Comment by jcbrand** [comment]
I'm still waiting for feedback on #283, which I tihnk is a blocker.

**Comment by damencho** [comment]
Thanks for the update.
