### ISSUE TITLE
Cannot use ver. 1.3.0 as standalone javascript library

### ISSUE THREAD

**Issue by luffyto21** [strophe/strophejs#311]
Hi, i updated my strophe version from 1.2.6 to latest one, 1.3.0 and cannot even instance a conecction object or add plugins due to the following errors:

"Strophe.Connection is not a constructor"
and "Strophe.addConnectionPlugin is not a function"

isnt Strophe on global scoope anymore?

can someone help me with this?

thx in advance.

**Comment by jcbrand** [comment]
It might be that the latest bundle doesn't but a Strophe object on the global scope anymore.
If so, that's a bug to be fixed.

Strophe 1.3.0 doesn't have any new features that aren't already in 1.2.16. The only changes are to use ES2015 modules and to have the bundle generated with webpack instead of r.js.

So for now you can simply use 1.2.16 to get the latest features and bugfixes.

**Comment by luffyto21** [comment]
ty for your reply.
im going to look for that version instead for now.

**Comment by alexandrmiee** [comment]
I use Vue
```
import Strophe from 'strophe.js'
var connection = Strophe.Strophe.Connection(WS_SERVICE);
```
and get 2 errors
```
TypeError: this.registerSASLMechanisms is not a function
TypeError: _this2._onIdle is not a function
```

**Comment by IPcorps** [comment]
Just try to insert at the beginning of the script:
`Object.assign(window, window.Strophe);`
