### ISSUE TITLE
Strophe Http-bind runs every second - ejabberd

### ISSUE THREAD

**Issue by devendrawebdeveloper** [strophe/strophejs#323]
I am using strophe for chat,"Connect" function is working fine.
After that on page load, I am using attach function but after attached, Strophe Http-bind runs every second with stanza.

Request:-

    <body rid="362421498" sid="0301cbe60c19d96a4e71f9dc6943ee774938cf48" xmlns="http://jabber.org/protocol/httpbind"/>  

Response:-

    <body xmlns='http://jabber.org/protocol/httpbind'/>

Every request running 2 times with same RID.

Code:-

            var sid = localStorage.getItem('sid');
			var rid = localStorage.getItem('rid');
			var jid = localStorage.getItem('jid');
			if(sid && rid && jid){
				jQuery(document).trigger('attach', {
					jid: jid,
					rid: rid,
					sid: sid,
				});
			}else{
				jQuery(document).trigger('connect', {
					jid: userdata.eusername.toLowerCase(),
					password: userdata.password
				});
			}

Thank you in advance.

**Comment by sualko** [comment]
I guess this solves your issue: http://strophe.im/strophejs/doc/1.3.0/files/strophe-js.html#Strophe.Connection.restore

**Comment by devendrawebdeveloper** [comment]
So first we need to use restore function then attach function.
Am i right?

**Comment by sualko** [comment]
> This function is only useful in conjunction with providing the “keepalive”:true option when instantiating a new Strophe.Connection.

I guess something like this should work (untested):
```
var conn = new Strophe.Connection('/http-bind/', {
   keepalive: true,
});

try {
  conn.restore(JID);
} catch() {
  conn.start(....);
}
```

Maybe you get an idea what `restore` does, if you look at the code: https://github.com/strophe/strophejs/blob/ac043ff0c13979ead61f94d19144f81e1dbeafe0/src/core.js#L1834-L1869

https://github.com/strophe/strophejs/blob/ac043ff0c13979ead61f94d19144f81e1dbeafe0/src/bosh.js#L295-L336

**Comment by devendrawebdeveloper** [comment]
@sualko Thankyou But it is not working .Please find the attachment for more detail.

If you have any idea?
![continous request send](https://user-images.githubusercontent.com/4918366/56156117-2b91de80-5fda-11e9-89e6-bb655e8ed877.png)
![multiple request with same Rid](https://user-images.githubusercontent.com/4918366/56156118-2b91de80-5fda-11e9-961e-93d9e0388b2d.png)

**Comment by jcbrand** [comment]
@devendrawebdeveloper Are you using `keepalive` and `restore` like @sualko suggested?

That's the best way to reattach to an existing session.

Looking at the network traffic, you're sending the same RID with every request, this is why it's not working for you. If you use `restore` then this won't happen, so I'm quite sure the problem is in your code and not in Strophe.

>  So first we need to use restore function then attach function.

No, you shouldn't call `attach` at all. Look at the code snippet that @sualko pasted.
Also look at the relevant docs: http://strophe.im/strophejs/doc/1.3.0/files/strophe-js.html#Strophe.Connection.restore

**Comment by devendrawebdeveloper** [comment]
I am using restore function.

**Comment by jcbrand** [comment]
You're answer is basically useless, since we don't know what else you are doing as well. You'll need to provide more information to show that this is an issue with Strophe.

I'm personally averse to providing general debugging support to people in the Github issue trackers.
The issue tracker should be for bug reports and feature requests, not to get experts to help you debug your code.
