### ISSUE TITLE
Access-control-allow-origin on register using strophe .

### ISSUE THREAD

**Issue by mailtosagar** [strophe/strophejs#333]
Hi ,
I just started working with ejabbred. I am using Strophe as client side library .

I am getting this error continuously when i am registring "new user" .

![image](https://user-images.githubusercontent.com/16096109/60341693-fab42980-99cc-11e9-870a-0210dc22bfda.png)

There is no "connected" status . I have tried the changing my ejabberd.yml file like this.

" port: 5280
ip: "::"
module: ejabberd_http
request_handlers:
"/admin": ejabberd_web_admin
"http-bind": true
"upload": mod_http_upload
custom_headers:
"Access-Control-Allow-Origin": "*"
"Access-Control-Allow-Methods": "OPTIONS, HEAD, GET, PUT"
"Access-Control-Allow-Headers": "Authorization"
"Access-Control-Allow-Credentials": "true".

and the same thing i have done below the line
mod_http_upload:
put_url: "https://@host@:5443/upload"

still i am getting the same error again and again with no change.
Please help as i have spent a lot of time over this.
Thanks in advance

**Comment by jcbrand** [comment]
This is a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) error because localhost:5280 and localhost:3000 are considered two different domains.

You need to configure your XMPP server to enable CORS or you can put a webserver such as NGinx in front of your BOSH endpoint so that it's served on the same domain as your website.
