### ISSUE TITLE
Stanzas not receiving by Clients.

### ISSUE THREAD

**Issue by mailtosagar** [strophe/strophejs#337]
Hi,
So far it's been a great library. I am making my own client using strophe. 
I am using ejabberd 19. So i am using 'http-bind'.
But i am facing an issue which is very strange. 
So i have two clients Alice and Cr7 . cr7 is online from the gajim and other is from my web client . 

When sending msg from
Alice to cr7 : No problem.
when sending from cr7 to alice: after a single msg, no message is received by alice. but still alice is able to send messages to cr7 and it is receiving .
What part i could possibely be missing in my client.

**Comment by jcbrand** [comment]
Sorry, this question is too vague for us to answer and this issue tracker is not for general support questions. Please only report bugs or feature requests.

**Comment by mailtosagar** [comment]
Well @jcbrand 
I think this is a bug as i am not seeing the what it means to happen. So please can you atleast give me a hint so if i can start searching out.

**Comment by jcbrand** [comment]
I seriously doubt it's a bug, since this is a mature library with many implementations.
That said, if you think it's a bug, then provide some kind of reproducible way in which we could verify that the bug exists.

Probably what's happening is that your event handler for incoming messages gets unsubscribed, probably because you're not returning `true` to keep it subcribed.

So... make sure your stanza handlers return `true` if they're supposed to continue handling stanzas.

**Comment by mailtosagar** [comment]
Thank you so much @jcbrand 
You saved my life just telling me that.
