### ISSUE TITLE
strophe sendIQ didn't callback on macOS 10.15.4

### ISSUE THREAD

**Issue by lwj06** [strophe/strophejs#348]
The same code, sendIQ method can callback on windows10 always, but there is no callback sometimes when I run it on macOS 10.15.4

**Comment by sualko** [comment]
It's not enough information to solve your issue. How can this be reproduced? Which browser or node version are you using?

I don't want to say that there could be no error in this lib, but it's used by a lot of people for a long time and the experience should that such errors are most of the time not related to this lib. So try to create a proof of concept, so that we can easily reproduce it.

**Comment by lwj06** [comment]
node 8.9.0, macOS 10.15.4,  electron 2.0.4 

elem.innerHtml:
<vCard xmlns="vcard-temp"><FN>lwj002</FN><NICKNAME>lwj002</NICKNAME><BDAY/><DEVICETOKEN/><LOGINNOTICE/><DEVICETYPE>pc</DEVICETYPE><APPVERSION>1.3.8</APPVERSION><USERID/><SEX>m</SEX><MOODMESSAGE/><PHOTO><BINVAL>L1VwbG9hZEZpbGVzL3dlYXIvYXZhdGFyLzIwMjAwNTExLzM1ZGRmOTQzMmY5ZjRlMjg5ZDM2ZTY1NjVmMDc3N2ZjLmpwZw==</BINVAL><TYPE>image/jpeg</TYPE></PHOTO><GMTTIME>8</GMTTIME></vCard>

![image](https://user-images.githubusercontent.com/5893392/81533461-d5d46500-9398-11ea-9e11-76b58b19c136.png)

**Comment by jcbrand** [comment]
What kind of error do you get when you call `stanza.getAttribute('type')`?

**Comment by lwj06** [comment]
> What kind of error do you get when you call `stanza.getAttribute('type')`?

iqtype='error'

**Comment by sualko** [comment]
From your code, I see that your issue is not that the callback is not called, instead the returning stanza has not the result you are expecting. As I said before, please provide a self containing example (not your whole program), so that we can reproduce your issue.
