### ISSUE TITLE
 Add Promise support to strophe.js

### ISSUE THREAD

**Issue by jinyu2022** [strophe/strophejs#763]
Dear strophe.js maintainers,

I've noticed that the project has been upgraded to ES6. However, the library still relies heavily on callback functions for asynchronous operations, rather than utilizing the more modern and elegant Promise-based approach.
Please consider adding Promise support to strophe.js. I believe this would be a valuable improvement for the library and its users.

**Comment by jcbrand** [comment]
Thanks for the suggestion.

Strophe works well the way it is written currently and the projects that currently rely on it aren't going to benefit much from promises being added since they already use the callbacks and probably have better things to do than to rewrite their code just to use promises.

The same applies to Strophe itself. I don't think the potential benefits of using promises outweigh the effort required to update Strophe, not to mention the opportunity cost of what else could have been done with the same time.

**Comment by jcbrand** [comment]
That said, if someone considers it worth their time to take a stab at adding a promises API for Strophe, you're more than welcome to do so and make a pull request.
