### ISSUE TITLE
release a 1.1.4 ? 

### ISSUE THREAD

**Issue by allan-simon** [strophe/strophejs#80]
Hello it would be kind to release a 1.1.4 has some issues has been fixed since 1.1.3 and this way people who used package managers to manage libraries will be able to take advantage of it 

thank you :)

**Comment by altrim** [comment]
Any update on this? Is there an estimation when it might be released?

**Comment by Gordin** [comment]
I just merged all the changes that @jcbrand pulled in here with my branch that implements the newest xmpp-over-websocket protocol.
I would like some people to test the current head and if there are no problems release this as a 1.2.0 because the newest xmpp-over-websocket probably breaks compatibility with with servers that have not yet adapted to it. (AFAIK all big servers have though).

**Comment by altrim** [comment]
I've been playing around this week with the current head. Looks like everything is fine, didn't get issues so far.

**Comment by Gordin** [comment]
@altrim thanks, while you're at it, do you mind trying out the https://github.com/strophe/strophejs/tree/amd-merge branch as well? ^^ I'd like to merge that before the next version as well if there are no problems.

**Comment by altrim** [comment]
@Gordin Switched to the `amd-merge` branch and used the generated `strophe.js`, didn't break anything, still working fine. I will keep playing around tomorrow and next week as well. If anything comes up I will let you know.

**Comment by isfarax** [comment]
would be good to support amd :)

**Comment by jcbrand** [comment]
Hi @Gordin, when are you planning on making this release? Any holdup?

**Comment by Gordin** [comment]
Just released a 1.2.0 (not 1.1.4 because WebSocket is probably incompatibly with older implementations that don't support the current RFC)
