### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by GeoffreyOnRails** [strophe/strophejs#9]
I open this discussion to pursue the one in metajack's branch (https://github.com/metajack/strophejs/issues/68)
I agree with michfield, I would also suggest to merge @Gordin branch. 
Is there any reason not to merge this branch/support websocket in strophe yet?

**Comment by rastkojokic** [comment]
Any examples of how to use web socket?

Thanks!

**Comment by Gordin** [comment]
You need an XMPP Server that has support for WebSocket connections. If you have that, just replace the BOSH connection URL with a WebSocket URL (usually ws://server.tld:5280/xmpp-websocket) and Strophe will use WebSockets instead of BOSH. Everything will work just as with BOSH otherwise.
Read the documentation for your server on how to setup WebSocket connections.

**Comment by rastkojokic** [comment]
Thanks @Gordin . That's all I needed!

Have a good day!
